# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systeminfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_info(object):
    def setupUi(self, info):
        info.setObjectName("info")
        info.resize(631, 372)
        self.centralwidget = QtWidgets.QWidget(info)
        self.centralwidget.setObjectName("centralwidget")
        self.cpu = QtWidgets.QLabel(self.centralwidget)
        self.cpu.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cpu.setFont(font)
        self.cpu.setObjectName("cpu")
        self.cpu_log = QtWidgets.QLabel(self.centralwidget)
        self.cpu_log.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cpu_log.setFont(font)
        self.cpu_log.setObjectName("cpu_log")
        self.cpus = QtWidgets.QLabel(self.centralwidget)
        self.cpus.setGeometry(QtCore.QRect(100, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cpus.setFont(font)
        self.cpus.setObjectName("cpus")
        self.cpu_logs = QtWidgets.QLabel(self.centralwidget)
        self.cpu_logs.setGeometry(QtCore.QRect(100, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cpu_logs.setFont(font)
        self.cpu_logs.setObjectName("cpu_logs")
        info.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(info)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 23))
        self.menubar.setObjectName("menubar")
        info.setMenuBar(self.menubar)

        self.retranslateUi(info)
        QtCore.QMetaObject.connectSlotsByName(info)

    def retranslateUi(self, info):
        _translate = QtCore.QCoreApplication.translate
        info.setWindowTitle(_translate("info", "系統資訊"))
        self.cpu.setText(_translate("info", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">CPU核心數:</span></p></body></html>"))
        self.cpu_log.setText(_translate("info", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">CPU邏輯數:</span></p></body></html>"))
        self.cpus.setText(_translate("info", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">0</span></p></body></html>"))
        self.cpu_logs.setText(_translate("info", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">0</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    info = QtWidgets.QMainWindow()
    ui = Ui_info()
    ui.setupUi(info)
    info.show()
    sys.exit(app.exec_())
