fun_list ={    
"b'CreateWindowExW'":'創建具有擴展窗口樣式的重疊窗口、彈出窗口或子窗口', 
"b'MessageBoxW'":'顯示一個模式對話框',
"b'MessageBoxA'":'顯示一個模式對話框',
"b'SystemParametersInfoW'":'檢索或設置系統範圍參數之一的值', 
"b'DestroyIcon'":'銷毀圖標並釋放圖標佔用的所有記憶體', 
"b'SetWindowLongW'":'更改指定窗口的屬性(x86)', 
"b'GetWindowLongW'":'檢索有關指定窗口的信息', 
"b'GetClientRect'":'檢索窗口客戶區的坐標', 
"b'InvalidateRect'":'將一個矩形添加到指定窗口的更新區域', 
"b'ReleaseDC'":'釋放設備上下文 (DC)，將其釋放以供其他應用程序使用', 
"b'GetDC'":'為指定窗口的客戶區或整個屏幕檢索設備上下文 (DC) 的句柄', 
"b'DrawTextW'":'在指定的矩形中繪製格式化文本', 
"b'GetDialogBaseUnits'":'檢索系統的對話框基本單位，即係統字體中字符的平均寬度和高度', 
"b'EndDialog'":'銷毀模態對話框，導致系統結束對對話框的任何處理', 
"b'DialogBoxIndirectParamW'":'從記憶體中的對話框模板創建模式對話框', 
"b'MoveWindow'":'更改指定窗口的位置和尺寸', 
"b'SendMessageW'":'將指定的消息發送到一個或多個窗口', 
"b'GetACP'":'檢索操作系統的當前 Windows ANSI 代碼頁標識符', 
"b'IsValidCodePage'":'確定指定的代碼頁是否有效', 
"b'GetStringTypeW'":'檢索指定 Unicode 源字符串中字符的字符類型信息', 
"b'GetFileAttributesExW'":'檢索指定文件或目錄的屬性', 
"b'FlushFileBuffers'":'刷新指定文件的緩衝區並將所有緩衝數據寫入文件', 
"b'GetCurrentDirectoryW'":'檢索當前進程的當前目錄', 
"b'GetOEMCP'":'返回操作系統的當前原始設備製造商 (OEM) 代碼頁標識符', 
"b'GetCPInfo'":'檢索有關任何有效的已安裝或可用代碼頁的信息', 
"b'GetModuleHandleW'":'檢索指定模塊的模塊句柄', 
"b'MulDiv'":'將兩個 32 位值相乘，然後將 64 位結果除以第三個 32 位值', 
"b'GetLastError'":'當有許多函式失敗時， GetLastError函式會傳回這些函數', 
"b'SetDllDirectoryW'":'將目錄添加到用於查找應用程序的 DLL 的搜索路徑', 
"b'GetModuleFileNameW'":'檢索包含指定模塊的文件的完全限定路徑', 
"b'GetProcAddress'":'明確連結至 DLL 呼叫 GetProcAddress 的進程，可取得 dll 中匯出函式的位址。 您可以使用傳回的函式指標來呼叫 DLL 函數', 
"b'GetEnvironmentStringsW'":'檢索當前進程的環境變量', 
"b'GetEnvironmentVariableW'":'從調用進程的環境塊中檢索指定變量的內容', 
"b'SetEnvironmentVariableW'":'為當前進程設置指定環境變量的內容', 
"b'ExpandEnvironmentStringsW'":'擴展環境變量字符串並將它們替換為為當前用戶定義的值', 
"b'CreateDirectoryW'":'創建一個新目錄', 
"b'GetTempPathW'":'檢索為臨時文件指定的目錄的路徑', 
"b'WaitForSingleObject'":'等待直到指定的對象處於信號狀態或超時間隔過去', 
"b'Sleep'":'暫停當前線程的執行，直到超時間隔過去', 
"b'GetExitCodeProcess'":'檢索指定進程的終止狀態', 
"b'CreateProcessW'":'創建一個新進程及其主線程', 
"b'GetStartupInfoW'":'檢索創建調用進程時指定的STARTUPINFO結構的內容', 
"b'FreeLibrary'":'釋放加載的動態鏈接庫 (DLL) 模塊，並在必要時減少其引用計數', 
"b'LoadLibraryExW'":'將指定的模塊加載到調用進程的地址空間中', 
"b'CloseHandle'":'關閉打開的對象句柄', 
"b'GetCurrentProcess'":'檢索當前進程的偽句柄', 
"b'LocalFree'":'釋放指定的本地內存對象並使其句柄無效', 
"b'FormatMessageW'":'格式化消息字符串', 
"b'MultiByteToWideChar'":'將字符串映射到 UTF-16(寬字符)字符串', 
"b'WideCharToMultiByte'":'將 UTF-16(寬字符)字符串映射到新字符串', 
"b'FreeEnvironmentStringsW'":'釋放環境字符串塊', 
"b'GetProcessHeap'":'檢索調用進程的默認堆的句柄', 
"b'GetTimeZoneInformation'":'檢索當前時區設置', 
"b'HeapSize'":'檢索HeapAlloc或 HeapReAlloc函數從堆中分配的內存塊的大小 ', 
"b'HeapReAlloc'":'從堆中重新分配一塊內存', 
"b'WriteConsoleW'":'從目前的游標位置開始，將字元字串寫入主控台螢幕緩衝區', 
"b'SetEndOfFile'":'將指定文件的物理文件大小設置為文件指針的當前位置', 
"b'GetCommandLineW'":'檢索當前進程的命令行字符串', 
"b'RtlUnwind'":'啟動過程調用幀的展開', 
"b'UnhandledExceptionFilter'":'如果正在調試進程，則應用程序定義的函數將未處理的異常傳遞給調試器', 
"b'SetUnhandledExceptionFilter'":'使應用程序能夠取代進程的每個線程的頂級異常處理程序', 
"b'TerminateProcess'":'終止指定進程及其所有線程', 
"b'IsProcessorFeaturePresent'":'確定當前計算機是否支持指定的處理器功能', 
"b'QueryPerformanceCounter'":'檢索性能計數器的當前值，這是一個高分辨率 (<1us) 時間戳，可用於時間間隔測量', 
"b'GetCurrentProcessId'":'檢索調用進程的進程標識符', 
"b'GetCurrentThreadId'":'檢索調用線程的線程標識符', 
"b'GetSystemTimeAsFileTime'":'檢索當前系統日期和時間', 
"b'InitializeSListHead'":'初始化單鍊錶的頭部', 
"b'IsDebuggerPresent'":'確定調用進程是否正在由用戶模式調試器調試', 
"b'DecodePointer'":'解碼以前使用EncodePointer編碼的指針', 
"b'SetLastError'":'設置調用線程的最後一個錯誤代碼', 
"b'EnterCriticalSection'":'等待指定臨界區對象的所有權', 
"b'LeaveCriticalSection'":'釋放指定臨界區對象的所有權', 
"b'DeleteCriticalSection'":'釋放無主臨界區對象使用的所有資源', 
"b'InitializeCriticalSectionAndSpinCount'":'初始化臨界區對象並設置臨界區的自旋計數', 
"b'TlsAlloc'":'分配線程本地存儲 (TLS) 索引', 
"b'TlsGetValue'":'檢索指定 TLS 索引的調用線程的線程本地存儲 (TLS) 槽中的值', 
"b'TlsSetValue'":'在調用線程的線程本地存儲 (TLS) 槽中存儲指定 TLS 索引的值', 
"b'TlsFree'":'釋放線程本地存儲 (TLS) 索引，使其可供重用', 
"b'RaiseException'":'支援 WRL 基礎結構，而且不適合直接從程式碼使用', 
"b'GetCommandLineA'":'檢索當前進程的命令行字符串', 
"b'CreateFileW'":'創建或打開文件或 I/O 設備', 
"b'GetDriveTypeW'":'確定磁盤驅動器是可移動驅動器、固定驅動器、CD-ROM、RAM 磁盤還是網絡驅動器', 
"b'GetFileInformationByHandle'":'檢索指定文件的文件信息', 
"b'GetFileType'":'檢索指定文件的文件類型', 
"b'PeekNamedPipe'":'將數據從命名或匿名管道複製到緩衝區而不將其從管道中刪除', 
"b'SystemTimeToTzSpecificLocalTime'":'將協調世界時 (UTC) 中的時間轉換為指定時區的對應本地時間', 
"b'FileTimeToSystemTime'":'將文件時間轉換為系統時間格式', 
"b'GetFullPathNameW'":'檢索指定文件的完整路徑和文件名', 
"b'RemoveDirectoryW'":'刪除現有的空目錄', 
"b'FindClose'":'關閉由 FindFirstFile、 FindFirstFile...函數打開的文件搜索句柄', 
"b'FindFirstFileExW'":'在目錄中搜索名稱和屬性與指定匹配的文件或子目錄', 
"b'FindNextFileW'":'從上一次調用 FindFirstFile、 FindFirstFileEx或 FindFirstFileTransacted函數繼續文件搜索', 
"b'SetStdHandle'":'設定指定標準裝置的控制碼 (標準輸入、標準輸出或標準錯誤)', 
"b'SetConsoleCtrlHandler'":'從呼叫程序的處理常式函式清單中新增或移除應用程式定義的 HandlerRoutine 函式', 
"b'DeleteFileW'":'刪除現有文件', 
"b'ReadFile'":'從指定的文件或輸入/輸出 (I/O) 設備讀取數據', 
"b'GetStdHandle'":'擷取指定標準裝置的控制代碼 (標準輸入、標準輸出或標準錯誤)', 
"b'WriteFile'":'將數據寫入指定的文件或輸入/輸出 (I/O) 設備', 
"b'ExitProcess'":'結束調用進程及其所有線程', 
"b'GetModuleHandleExW'":'檢索指定模塊的模塊句柄並增加模塊的引用計數', 
"b'HeapFree'":'釋放HeapAlloc或 HeapReAlloc函數從堆中分配的內存塊', 
"b'GetConsoleMode'":'抓取主控台之輸入緩衝區的目前輸入模式，或主控台螢幕緩衝區目前的輸出模式', 
"b'ReadConsoleW'":'從主控台輸入緩衝區讀取字元輸入，並將它從緩衝區中移除', 
"b'SetFilePointerEx'":'移動指定文件的文件指針', 
"b'GetConsoleOutputCP'":'抓取與呼叫進程相關聯的主控台所使用的輸出字碼頁', 
"b'GetFileSizeEx'":'檢索指定文件的大小', 
"b'HeapAlloc'":'從堆中分配一塊內存。分配的內存不可移動', 
"b'CompareStringW'":'比較由標識符指定的語言環境的兩個字符串', 
"b'LCMapStringW'":'對於標識符指定的語言環境，使用指定的轉換將一個輸入字符串映射到另一個，或者為輸入字符串生成一個排序鍵', 
"b'OpenProcessToken'":'OpenProcessToken函數打開與進程關聯的訪問令牌', 
"b'GetTokenInformation'":'GetTokenInformation函數檢索有關訪問令牌的指定類型的信息', 
"b'ConvertStringSecurityDescriptorToSecurityDescriptorW'":'onvertStringSecurityDescriptorToSecurityDescriptor函數將字符串格式的安全描述符轉換為有效的功能安全描述符', 
"b'ConvertSidToStringSidW'":'ConvertSidToStringSid函數將安全標識符(SID) 轉換為適合顯示、存儲或傳輸的字符串格式', 
"b'SelectObject'":'SelectObject函數將對象選擇到指定的設備上下文 (DC) 中', 
"b'DeleteObject'":'DeleteObject函數刪除邏輯筆、畫筆、字體、位圖、區域或調色板,釋放與對象關聯的所有系統資源', 
"b'CreateFontIndirectW'":'CreateFontIndirect函數創建具有指定特徵的邏輯字體'
}

virus = []