# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QTimer
import win32api,win32con
from PyQt5.QtWidgets import QMessageBox

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("UAC")
        Dialog.resize(521, 381)
        key = win32api.RegOpenKey(win32con.HKEY_LOCAL_MACHINE,'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System',0,win32con.KEY_ALL_ACCESS)
        EnableLUA, a= win32api.RegQueryValueEx(key, 'EnableLUA')
        ConsentPromptBehaviorAdmin, a= win32api.RegQueryValueEx(key, 'ConsentPromptBehaviorAdmin')
        PromptOnSecureDesktop, a= win32api.RegQueryValueEx(key, 'PromptOnSecureDesktop')
        self.sliderv = 0
        if ConsentPromptBehaviorAdmin == 2 and EnableLUA == 1 and PromptOnSecureDesktop == 1:
            self.sliderv = 3
        elif ConsentPromptBehaviorAdmin == 5 and EnableLUA == 1 and PromptOnSecureDesktop == 1:
            self.sliderv = 2
        elif ConsentPromptBehaviorAdmin == 5 and EnableLUA == 1 and PromptOnSecureDesktop == 0:
            self.sliderv = 1
        elif ConsentPromptBehaviorAdmin == 0 and EnableLUA == 1 and PromptOnSecureDesktop == 0:
            self.sliderv = 0
        self.Slider = QtWidgets.QSlider(Dialog)
        self.Slider.setGeometry(QtCore.QRect(50, 90, 22, 251))
        self.Slider.setMaximum(3)
        self.Slider.setOrientation(QtCore.Qt.Vertical)
        self.Slider.setObjectName("Slider")
        self.text = QtWidgets.QLabel(Dialog)
        self.text.setGeometry(QtCore.QRect(40, 10, 411, 51))
        self.text.setBaseSize(QtCore.QSize(0, 0))
        self.text.setObjectName("text")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(150, 80, 331, 221))
        self.listView.setObjectName("listView")
        self.OK = QtWidgets.QPushButton(Dialog)
        self.OK.setGeometry(QtCore.QRect(410, 340, 75, 23))
        self.OK.setObjectName("OK")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 90, 311, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 120, 301, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.up = QtWidgets.QLabel(Dialog)
        self.up.setGeometry(QtCore.QRect(30, 60, 61, 21))
        self.up.setAlignment(QtCore.Qt.AlignCenter)
        self.up.setObjectName("up")
        self.down = QtWidgets.QLabel(Dialog)
        self.down.setGeometry(QtCore.QRect(30, 350, 61, 21))
        self.down.setAlignment(QtCore.Qt.AlignCenter)
        self.down.setObjectName("down")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(170, 150, 301, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("UAC", "UAC"))
        self.text.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">請選擇UAC通知時機</span></p></body></html>"))
        self.OK.setText(_translate("Dialog", "OK"))
        self.OK.clicked.connect(self.setuac)
        self.up.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">一律通知</span></p></body></html>"))
        self.down.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">不要通知</span></p></body></html>"))
        self.Slider.setValue(self.sliderv)
        self.timer=QTimer()
        self.timer.timeout.connect(self.updatetext)
        self.timer.start(100)

    def updatetext(self):
        _translate = QtCore.QCoreApplication.translate
        self.value = self.Slider.value()
        if self.value == 0:
            self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">發生下列狀況時，不要通知我:</span></p></body></html>"))
            self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">1.應用程式嘗試安裝軟體或變更我的電腦</span></p></body></html>"))
            self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">2.我變更Windows設定</span></p></body></html>"))
        elif self.value == 1:
            self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:13.5pt;\">應用程式嘗試變更我的電腦時才通知我</span></p></body></html>"))
            self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">1.當我變更Windows設定時，不要通知我。</span></p></body></html>"))
            self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\"></span></p></body></html>"))
        elif self.value == 2:
            self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">只在應用程式嘗試變更我的電腦時才通知我</span></p></body></html>"))
            self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">1.當我變更Windows設定時，不要通知我。</span></p></body></html>"))
            self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\"></span></p></body></html>"))
        elif self.value == 3:
            self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">發生下列狀況時一律通知我:</span></p></body></html>"))
            self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">1.應用程式嘗試安裝軟體或變更我的電腦</span></p></body></html>"))
            self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">2.我變更Windows設定</span></p></body></html>"))

    def setuac(self):
        ques = QMessageBox.warning(None,'UAC','確定要修改UAC通知等級嗎?',QMessageBox.Yes|QMessageBox.No,QMessageBox.Yes)
        if ques == 16384:
            self.value = self.Slider.value()
            key = win32api.RegOpenKey(win32con.HKEY_LOCAL_MACHINE,'SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System',0,win32con.KEY_ALL_ACCESS)
            if self.value == 0:
                try:
                    win32api.RegSetValueEx(key, 'EnableLUA' , 0, win32con.REG_DWORD, 1)
                    win32api.RegSetValueEx(key, 'ConsentPromptBehaviorAdmin' , 0, win32con.REG_DWORD, 0)
                    win32api.RegSetValueEx(key, 'PromptOnSecureDesktop' , 0, win32con.REG_DWORD, 0)
                    QMessageBox.information(None,'Done','設定UAC通知等級成功!',QMessageBox.Ok,QMessageBox.Ok)
                except:
                    QMessageBox.critical(None,'error','發生錯誤!',QMessageBox.Ok,None)
            elif self.value == 1:
                try:
                    win32api.RegSetValueEx(key, 'EnableLUA' , 0, win32con.REG_DWORD, 1)
                    win32api.RegSetValueEx(key, 'ConsentPromptBehaviorAdmin' , 0, win32con.REG_DWORD, 5)
                    win32api.RegSetValueEx(key, 'PromptOnSecureDesktop' , 0, win32con.REG_DWORD, 0)
                    QMessageBox.information(None,'Done','設定UAC通知等級成功!',QMessageBox.Ok,QMessageBox.Ok)
                except:
                    QMessageBox.critical(None,'error','發生錯誤!',QMessageBox.Ok,None)
            elif self.value == 2:
                try:
                    win32api.RegSetValueEx(key, 'EnableLUA' , 0, win32con.REG_DWORD, 1)
                    win32api.RegSetValueEx(key, 'ConsentPromptBehaviorAdmin' , 0, win32con.REG_DWORD, 5)
                    win32api.RegSetValueEx(key, 'PromptOnSecureDesktop' , 0, win32con.REG_DWORD, 1)
                    QMessageBox.information(None,'Done','設定UAC通知等級成功!',QMessageBox.Ok,QMessageBox.Ok)
                except:
                    QMessageBox.critical(None,'error','發生錯誤!',QMessageBox.Ok,None)
            elif self.value == 3:
                try:
                    win32api.RegSetValueEx(key, 'EnableLUA' , 0, win32con.REG_DWORD, 1)
                    win32api.RegSetValueEx(key, 'ConsentPromptBehaviorAdmin' , 0, win32con.REG_DWORD, 2)
                    win32api.RegSetValueEx(key, 'PromptOnSecureDesktop' , 0, win32con.REG_DWORD, 1)
                    QMessageBox.information(None,'Done','設定UAC通知等級成功!',QMessageBox.Ok,QMessageBox.Ok)
                except:
                    QMessageBox.critical(None,'error','發生錯誤!',QMessageBox.Ok,None)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
